### ISSUE TITLE
The FeaturePack.ConfigureServices.ps1 fails with "Exiting.... Could not find BizTalk Server Installation Folder."

### ISSUE THREAD

**Issue by jamesemann** [MicrosoftDocs/biztalk-docs#283]
regarding https://github.com/MicrosoftDocs/biztalk-docs/blob/live/biztalk/core/configure-the-operational-data-feed-for-power-bi-with-biztalk-server.md

The FeaturePack.ConfigureServices.ps1 fails with the following error:

``Exiting.... Could not find BizTalk Server Installation Folder.``

Seems to be related to the version of PowerShell. I am using PowerShell 4 and the command Get-ItemPropertyValue not being available:

```
Get-ItemPropertyValue : The term 'Get-ItemPropertyValue' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Microsoft\BizTalk Server\3.0' -Name  ...
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ItemPropertyValue:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I was able to work around it by commenting out the checks on lines 47-61 and hardcoding the $BizTalkInstallPath to "C:\Program Files (x86)\Microsoft BizTalk Server 2016". 

Obviously not a long term fix.

**Comment by MandiOhlinger** [comment]
@jamesemann Thank you for letting us know about this. Our product group tested, and it seems to be an issue with the PowerShell version. This will be fixed in an upcoming BizTalk 2016 feature pack or cumulative update.
