### ISSUE TITLE
Error Biztalk connect to SQL managed instances ( deployment option of Azure SQL Database )

### ISSUE THREAD

**Issue by cloudmelon** [MicrosoftDocs/biztalk-docs#293]
Whiling trying to configure Biztalk server, it fails to connect to SQL managed instance ( or Azure SQL database connection string ), I followed the doc and tried the following URI with schema:
mssql://
jdbc:sqlserver://

mssql://xxxxxxx.xxxxx26.database.windows.net//  
mssql://xxxxx.database.windows.net// 

![image](https://user-images.githubusercontent.com/4621560/46527730-56181780-c892-11e8-95c8-82f998461ae5.png)

Could you please check that ? Thank you :)

URL doc : 
https://docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/adapter-sql/create-the-sql-server-connection-uri

**Comment by MandiOhlinger** [comment]
@cloudmelon Did you get this fixed? If yes, what'd you do? We can definitely add some guidance to this topic on how you resolved it. If it's not fixed, I suggest posting this question to the forums for some help.

**Comment by cloudmelon** [comment]
Hi Mandi, I tried multiple times without success. Please post it to the forums. Many thanks :)

Melony

**Comment by MandiOhlinger** [comment]
@cloudmelon Ok. You should post, including steps you've tried. To post, go to https://social.msdn.microsoft.com/forums/biztalk/en-us/home?category=biztalkserver, and select the forum that works for your scenario.

**Comment by cloudmelon** [comment]
Hi @MandiOhlinger  Thank you for your information. I'll update it accordingly. I retest with Azure VM hosts Biztalk 2013 R2 and another VM deployed with SQL Server 2014, and it is working ( as I supposed ). I do think there is some issues with managed SQL instances under this scenario. Thanks anyways :)
