### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by Ramendra30** [MicrosoftDocs/biztalk-docs#387]
https://msdn.microsoft.com/library/59895616-4178-46d0-b9ff-95589b809ff5

**Comment by MandiOhlinger** [comment]
@Ramendra30 Which article?

**Comment by MandiOhlinger** [comment]
Fixed links in https://docs.microsoft.com/en-us/biztalk/core/how-to-cluster-sso-and-a-biztalk-host-in-the-same-cluster-group1. Changes will be live later today.
