### ISSUE TITLE
Documentation of the process taken by the Deploy BizTalk Application pipeline task should be more specific for cases of multiple machines

### ISSUE THREAD

**Issue by TWolverson** [MicrosoftDocs/biztalk-docs#391]
The documentation at https://docs.microsoft.com/en-us/biztalk/core/feature-pack-add-build-release-definitions does not specify what happens if the Group contains multiple computers. It should also be more explicit about the differences between the three options, as this is not very clearly explained.

**Comment by MandiOhlinger** [comment]
@TWolverson You are correct. If you have any additional information to add, it's very welcome. Currently, we have no plans to expand our guidance using VSTS. If you find another resource, such as a VSTS link, we can also add that. Just something to consider in case you have more information.
