### ISSUE TITLE
Conflicting statements in note about BRE Call Rules

### ISSUE THREAD

**Issue by eloekset** [MicrosoftDocs/biztalk-docs#429]
In the first tip of [this paragraph](https://github.com/MicrosoftDocs/biztalk-docs/blob/live/biztalk/core/how-to-use-the-call-rules-shape.md#to-configure-the-call-rules-shape), BizTalk Server is mentioned twice with conflicting statements. I guess one of them applies to Visual Studio, while the other one applies to BizTalk Server Administration Console.

**Comment by eloekset** [comment]
*In **BizTalk Server**, you do not need to have an atomic scope to insert a Call Rules shape. You can drag a Call Rules shape into the Orchestration Design Surface from the Toolbox. **However, in BizTalk Server**, the Call Rules menu item is disabled in the context menu if you try to insert a Call Rules shape inside an orchestration that does not have an atomic scope. This is a limitation with the BizTalk Server product.*

**Comment by clineer** [comment]
Maybe make a PR and edit the second one to say "However, in Visual Studio," instead. Let me know if you need help making the PR. I would be glad to do it.

**Comment by eloekset** [comment]
Are we sure the second one applies to Visual Studio? That's why I didn't create a PR with a proposed change. I'm not really sure what's correct. But I would guess the first sentence is about Visual Studio, since it mentions an Orchestration Design Surface and Toolbox. 🤔

**Comment by MandiOhlinger** [comment]
@eloekset @clineer We clarified the note. And, this limitation is fixed in BizTalk 2016. Not sure about BizTalk 2013 or 2013 R2. Changes should be live shortly.
