### ISSUE TITLE
ADDLOCAL list of features (BTS 2016)

### ISSUE THREAD

**Issue by SanderHolvoet** [MicrosoftDocs/biztalk-docs#466]
Please update the list of features which can be used during a silent install of BTS 2016, by specifying the _ADDLOCAL_ parameter. This currently points to a [blog post](https://social.technet.microsoft.com/wiki/contents/articles/571.listing-of-values-for-the-addlocal-command-when-performing-a-silent-installation-of-biztalk-server-2010.aspx) which is nearly 10 years old, and was originally intended for _BizTalk Server 2010_.

See [Appendix A: Silent Installation](https://docs.microsoft.com/en-us/biztalk/install-and-config-guides/appendix-a-silent-installation).

**Comment by MandiOhlinger** [comment]
@SanderHolvoet If you have this information, please add it in a pull request. If you're not sure, it's best to open a support case, and get this info. Then, the support person can update this article.
