### ISSUE TITLE
XSLT 3.0 Links are not valid

### ISSUE THREAD

**Issue by Manish-Upadhyaya** [MicrosoftDocs/biztalk-docs#478]
Links related to XSL 3.0 announcement are not valid. 

https://github.com/MicrosoftDocs/biztalk-docs/blob/sandbox/biztalk/install-and-config-guides/whats-new-in-biztalk-server-2020.md

404 for these links:
https://docs.microsoft.com/en-us/biztalk/core/technical-reference/xslt-transform-engine-grid-property

https://docs.microsoft.com/en-us/biztalk/core/technical-reference/xslt-custom-transform-implementation

**Comment by MandiOhlinger** [comment]
Correct. Those links aren't live yet.
