### ISSUE TITLE
BizTalk API Link and Page title has typo

### ISSUE THREAD

**Issue by clineer** [MicrosoftDocs/biztalk-docs#483]
I was looking at the BizTalk REST API and under Operational data it has a typo on AS2. 

Here is the link - https://docs.microsoft.com/en-us/rest/api/biztalk/operationaldata/getas2statusrecords?view=rest-biztalk-2016. You see it says "Operational Data - Get A S2 Status Records" with an extra space between A and S in the AS2 abbreviation. 

I could not find the page here on Github to correct it. If you tell me where to find the page I can submit a fix for it.

**Comment by MandiOhlinger** [comment]
@clineer Thank you. This file is created and updated by engineering, and isn't available in a public-facing repo.

That being said, we looked at the file, and the space isn't there. We suspect the space is auto-added by tooling when these json files are published.

We'll try to get it fixed. But honestly, it's not a priority.

**Comment by clineer** [comment]
Thanks @MandiOhlinger. No problem about the priority.

**Comment by msnehagup** [comment]
This is fixed.
