### ISSUE TITLE
Conflicting supported .NET Framework versions in documentation

### ISSUE THREAD

**Issue by Pauwelz** [MicrosoftDocs/biztalk-docs#484]
With the release of BizTalk 2020 there are some conflicting statements about the required .NET Framework version

In the [Hardware and Software Requirements for BizTalk Server 2020](https://docs.microsoft.com/en-us/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2020) the supported .NET version is stated as **4.7**
However under the [Visual Studio 2019](https://docs.microsoft.com/en-us/biztalk/install-and-config-guides/set-up-and-install-prerequisites-for-biztalk-server-2020#install-visual-studio-2019-optional) part of [Set up and install prerequisites for BizTalk Server 2020](https://docs.microsoft.com/en-us/biztalk/install-and-config-guides/set-up-and-install-prerequisites-for-biztalk-server-2020) it states .NET Framework **4.7.2**

Which is the correct supported version? I would assume it's 4.7.2

**Comment by SanjivGupta-SanGupt** [comment]
Yes, you can't go wrong with assuming 4.7.2
4.7 means the min version. 
If you run your developer tools on a machine other than where you have BizTalk runtime, you can also have the machine where VS is installed 4.7.2 where as the other machines can have 4.7
