### ISSUE TITLE
Office 365 Outlook Email adapter - endpoint Payload properties

### ISSUE THREAD

**Issue by erwinkramer** [MicrosoftDocs/biztalk-docs#510]
The **endpoint Payload properties** for the Office 365 Outlook Email adapter are not actually visible for BizTalk 2016 with feature pack 3, i'm assuming it's a feature only for BizTalk 2020 and not for BizTalk 2016 with feature pack 3? Could you perhaps clarify this in the docs:
https://docs.microsoft.com/en-us/biztalk/core/office365-mail-adapter#receive-email-using-a-receive-port

**Comment by mvelmurugan** [comment]
Is there any update regarding the end point payload properties are not visible in Biztalk 2016 please ?

**Comment by MandiOhlinger** [comment]
@erwinkramer @mvelmurugan Good catch. Thank you! The **Payload** settings are available starting with BizTalk Server 2020 and newer. The article now states this, and changes should be live later today.
