### ISSUE TITLE
SFTP property 'Maximum Connection Reuse Time In Seconds' missing in docs

### ISSUE THREAD

**Issue by erwinkramer** [MicrosoftDocs/biztalk-docs#565]
The SFTP adapter has a new property (since BizTalk 2016 CU7 I believe) and it's called 'Maximum Connection Reuse Time In Seconds' (or MaxConnectionReuseTimeInSeconds in the bindings). There is a brief explanation in the adapter itself, but it would be nice to have it documented at this page: https://docs.microsoft.com/en-us/biztalk/core/sftp-adapter.

**Comment by MandiOhlinger** [comment]
@erwinkramer Thank you. It'd be great if you created a pull request (PR) with this information. We review every PR, so know that we've got your back. 

The steps to create a PR are at [https://github.com/MicrosoftDocs/biztalk-docs](https://github.com/MicrosoftDocs/biztalk-docs). Just scroll past the folder view.

**Comment by erwinkramer** [comment]
@MandiOhlinger I can't document your product for you when i don't even know exactly what it does, i'm sorry.

**Comment by MandiOhlinger** [comment]
@ErikMogensen Thank you for adding the description. Much appreciated. If I ever see you in person, I owe you a beer.
