### ISSUE TITLE
Link to information on 'Create SSIS Catalog' does not work

### ISSUE THREAD

**Issue by Andy-Dawson** [MicrosoftDocs/biztalk-docs#567]
The link in the section 'SSIS Catalog (SSIDB): Optional. Required to use BAM.' is wrong and gives a 404 error.

I believe the link should be: https://docs.microsoft.com/en-us/sql/integration-services/catalog/ssis-catalog?view=sql-server-ver15#create-the-ssis-catalog (it is currently https://docs.microsoft.com/en-us/sql/integration-services/create-the-ssis-catalog).

**Comment by MandiOhlinger** [comment]
@Andy-Dawson Thank you. It'd be great if you created a pull request (PR) in the article with the correct link. We review every PR before we merge it.

The steps to create a PR are at [https://github.com/MicrosoftDocs/biztalk-docs](https://github.com/MicrosoftDocs/biztalk-docs). Just scroll past the folder view.

**Comment by CarloGarcia** [comment]
Hi, I have created a PR with a fix for this here:
https://github.com/MicrosoftDocs/biztalk-docs/pull/584

**Comment by MandiOhlinger** [comment]
@CarloGarcia Thank you for fixing this. Much appreciated :).
