### ISSUE TITLE
Missing prereq

### ISSUE THREAD

**Issue by dnsinit** [MicrosoftDocs/biztalk-docs#577]
Missing a prereq in the [HL7 documentation](https://docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/accelerator-hl7/install-biztalk-accelerator-for-hl7). If you haven't installed Microsoft SQL Server Native Client, you will be stuck with errors when connecting to the SQL server through the installation wizard (even though it works fine when connecting from BizTalk or by testing with a .udl file).

Error message:
Setup cannot proceed because it failed to connect to SQL Server named "SQLServerName". Start the SQL server to correct the problem.

**Comment by ecfan** [comment]
Created work item and assigned to product team.
