### ISSUE TITLE
Code fragment for programmatically creating send port including behavior does not work.

### ISSUE THREAD

**Issue by niclas-colleen** [MicrosoftDocs/biztalk-docs#582]
The code below will generate error "Invalid or malformed XML data." on last line: explorer.SaveChanges().
Does anyone have any documentation on how EndpointBehaviorConfiguration is handlede by ExplorerOM? Removing the node <callbackTimeouts /> will allow the send port to be created. So I believe ExplorerOM is checking against a schema and it is not expecting the node. 

        public static void CreateSendPort()
        {
                string transportConfigData = @"<CustomProps>
                                 <StaticAction vt=""8"">http://www.northwindtraders.com/Service/Operation</StaticAction>
                                 <EndpointBehaviorConfiguration vt=""8""><behavior name=""sampleBehavior""><callbackTimeouts /></behavior></EndpointBehaviorConfiguration>
                                 <BindingType vt=""8"">netNamedPipeBinding</BindingType>
                               </CustomProps>";
                string server = System.Environment.MachineName;
                string database = "BizTalkMgmtDb";
                string connectionString = string.Format("Server={0};Database={1};Integrated Security=true", server, database);
                //requires project reference to \Program Files\Microsoft BizTalk Server 2009\Developer Tools\Microsoft.BizTalk.ExplorerOM.dll
                BtsCatalogExplorer explorer = new Microsoft.BizTalk.ExplorerOM.BtsCatalogExplorer();
                explorer.ConnectionString = connectionString;

                // Add a new BizTalk application
                Application application = explorer.Applications["FoodFolk"];

                // Add a new static one-way send port
                SendPort sendPort = application.AddNewSendPort(false, false);
                sendPort.Name = "SampleSendPort";
                sendPort.PrimaryTransport.TransportType = explorer.ProtocolTypes["WCF-Custom"];
                sendPort.PrimaryTransport.Address = "net.pipe://mycomputer/private/samplequeue";
                sendPort.PrimaryTransport.TransportTypeData = transportConfigData; // propertyData; // need to change
                sendPort.SendPipeline = explorer.Pipelines["Microsoft.BizTalk.DefaultPipelines.PassThruTransmit"];
                // Save
                explorer.SaveChanges();
        }

**Comment by MandiOhlinger** [comment]
@niclas-colleen This is a good question. I suggest also posting it in the BizTalk community forums. The forums have a bigger audience. 

Also, when you get the answer, it'd be great if you created a pull request with your recommended doc changes.

**Comment by ecfan** [comment]
Created work item and assigned to product team.
