### ISSUE TITLE
DTCTester returns 404

### ISSUE THREAD

**Issue by CloudViking86** [MicrosoftDocs/biztalk-docs#744]
Hello,

Trying to download "DTCTester", I've tried w. "DTCPing" but the other machine I am testing against is an AWS RDS i.e. I don't have any access to the underlying operating system of the server and can run "DTCPing" on the other end.

Anyway when I try and download "DTCTester" this link;
https://support.microsoft.com/en-US/help/293799
returns 404, is there any other link to an official Microsoft download for "DTCTester"?

Best Regards - Karl

**Comment by ecfan** [comment]
Closing this thread due to no information available.
