### ISSUE TITLE
The space after the atmark in the command is not needed

### ISSUE THREAD

**Issue by nobuko-yamada** [MicrosoftDocs/biztalk-docs#876]
https://github.com/MicrosoftDocs/biztalk-docs/blob/2c21d4a6bb774b4ebcd7abee5e395d504fbda46b/his/install-and-config-guides/server-to-server-migration-2020.md?plain=1#L63

Command is saying that 
```
SNACFG.exe #”C:\Program Files\Microsoft Host Integration Server\System\config\com.cfg”  @ C:\Files\HIS_Migrate\System\Config\HISconfig.txt /NOVALIDATEPRINTER  /V
```

But because there is a space between @ (at mark) and the path of  "HISconfig.txt", the command causes error as below
(Error opening command file)

![image](https://github.com/MicrosoftDocs/biztalk-docs/assets/115044612/5a6d3eb1-5dc6-4da2-9339-d5178a7cf7ed)

I could succeed by the command like `SNACFG.exe #”C:\Program Files\Microsoft Host Integration Server\System\config\com.cfg”  @C:\Files\HIS_Migrate\System\Config\HISconfig.txt /NOVALIDATEPRINTER  /V`

**Comment by ecfan** [comment]
Created work item and assigned to product team.
