### ISSUE TITLE
Office 365 Outlook Email adapter does not have properties CC, To on Receive Port

### ISSUE THREAD

**Issue by Sethu-Neu** [MicrosoftDocs/biztalk-docs#881]
![image](https://github.com/MicrosoftDocs/biztalk-docs/assets/122597786/9587a25c-00ea-4a8a-93e4-485c8dc723df)

Whene we are receiving an email on the receive location , we have only few properties like Importance, Subject, SenderName, SenderAddress, HasAttachments but don't have **_To and CC addresses_**.

**Comment by ecfan** [comment]
Created work item and assigned to product team.
